import "./globals.css";
import Navigation from "@/components/Navigation";
export const metadata = {
  title: "Firs project in Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.tailwindcss.com" rel="stylesheet" />
      </head>
      <body>
        <div>
          <Navigation></Navigation>
        </div>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
